name: spotify_clone
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  just_audio: ^0.9.37
  audio_service: ^0.18.12
  cached_network_image: any
  flutter_native_splash: ^2.4.0
  http: ^1.2.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.6
  firebase_database: ^10.4.5
  firebase_storage: ^11.7.0
  cloud_firestore: ^4.17.2
  connectivity_plus: ^6.0.3
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/google_logo.png
    - assets/lang/
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"